### PR TITLE
implemented full portal feature in game

### PR DESCRIPTION
**Pull request by waihins**

### CODE REVIEW

**Comment by DavidLi1355** [comment]
The feature works as intended, the logic makes sense. 
Looks good to me.

**Comment by waihins** [comment]
https://user-images.githubusercontent.com/74951277/230493459-f41e9018-9c56-4432-81c7-572749165b08.mov

front-end changes after implementing portal feature

**Comment by DavidLi1355** [comment]
See #27 for unit testing.

**Comment by DavidLi1355** [comment]
#27 also includes formatting.

**Review by Mayojet — APPROVED** [review]
Looks good to me

**Pull request merged**
